### ISSUE TITLE
Fix and make tests for shit that @dequis found

### ISSUE THREAD

**Issue by qpfiffer** [infoforcefeed/OlegDB#155]
http://dump.dequis.org/UvO3B.txt
http://dump.dequis.org/BTRb6.txt
http://dump.dequis.org/quRWd.txt
http://dump.dequis.org/zr9kC.txt
http://dump.dequis.org/RrdXn.txt
http://dump.dequis.org/zPXRF.txt
http://dump.dequis.org/U92R0.txt

Might be simple, might not.

**Comment by dequis** [comment]
hi i'm @dequisfound

**Comment by qpfiffer** [comment]
I don't know what you're talking about everything I do is correct the first time

**Comment by dequis** [comment]
I was about to change my legal name but sure that's fine too

**Comment by qpfiffer** [comment]
Should be fixed as of a81504611f48fd4ca9b983ee5daed734962f9dd8
