### ISSUE TITLE
Directions to uninstall

### ISSUE THREAD

**Issue by breerly** [infoforcefeed/OlegDB#162]
How would I uninstall OlegDB from OSX? Thanks

**Comment by Xe** [comment]
Did you try deleting the files from /usr/local?

**Comment by qpfiffer** [comment]
@breerly Just delete the olegdb files in `/usr/local/bin`, `/usr/local/lib` and `/usr/local/include`.

I guess we should have an `uninstall` Makefile option. But then again who uninstalls software?

**Comment by breerly** [comment]
Thanks, that worked :)

**Comment by kyleterry** [comment]
`make uninstall` also works: https://github.com/infoforcefeed/OlegDB/blob/master/Makefile#L60

**Comment by colby** [comment]
fixed in 26cc073d150787718f1672ff861994636c1b01fa
