### ISSUE TITLE
THIS PROJECT ISN'T FAMOUS ENOUGH

### ISSUE THREAD

**Issue by lykkin** [infoforcefeed/OlegDB#164]

**Comment by Xe** [comment]
WE OBVIOUSLY NEED TO CONQUEROR THE MARTIANS LIKE SANTA CLAUS DID!

**Comment by kyleterry** [comment]
:shipit:

**Comment by dequis** [comment]
:package:

**Comment by qpfiffer** [comment]
We already have a shitposting area what is this nonsense :haircut:

**Comment by Hamcha** [comment]
What do you mean, nonsense? Shitposting on the issue tracker is gonna put OlegDB into datacenters, as you can see in this image:
![OlegDB Cluster is your mayo solution for enterprise needs](http://i.imgur.com/OIlhTJm.png).

**Comment by dequis** [comment]
This issue is **important**

**Comment by Hamcha** [comment]
TIL I can edit people comments
**I AM GOD**

**Comment by lykkin** [comment]
there is no single greater issue than this, i implore you, @qpfiffer, to take this seriously

**Comment by Xe** [comment]
I wanna be the guy is an amazing game

**Comment by colby** [comment]
This conflicts with master.
